apiVersion: v1
kind: PersistentVolume
metadata:
  name: www-pv-0
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data0"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: www-pv-1
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data1"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: www-pv-2
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data2"

